# Generated by Django 5.2.1 on 2025-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0002_alter_food_eaten_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='date_eaten',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
