# Generated by Django 5.2.1 on 2025-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0003_alter_food_eaten_date_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='date_eaten',
            field=models.DateTimeField(auto_now_add=True, verbose_name="['%Y-%m-%d %H:%M']"),
        ),
    ]
