# Generated by Django 5.2.1 on 2025-07-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0004_alter_food_eaten_date_eaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meals',
        ),
        migrations.AddField(
            model_name='food_eaten',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calories_tracker.meal'),
        ),
        migrations.AlterField(
            model_name='food_eaten',
            name='date_eaten',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
