# Generated by Django 5.2.1 on 2025-07-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0005_remove_meal_meals_food_eaten_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods_eaten', to='calories_tracker.meal'),
        ),
    ]
