# Generated by Django 5.2.1 on 2025-07-18 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0006_alter_food_eaten_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'name', 'date')},
        ),
    ]
