# Generated by Django 5.2.1 on 2025-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0007_alter_meal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='date_eaten',
            field=models.DateTimeField(),
        ),
    ]
